
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Kitapİlan
{

    public Kitapİlan()
    {

        this.Yorum = new HashSet<Yorum>();

    }


    public int Id { get; set; }

    public string Baslik { get; set; }

    public string KitapSayfaNo { get; set; }

    public string KitapFiyat { get; set; }

    public System.DateTime KitapTarih { get; set; }

    public int UserId { get; set; }

    public int KategoriId { get; set; }

    public int KitapDetayId { get; set; }

    public byte[] Resim { get; set; }



    public virtual User User { get; set; }

    public virtual Kategori Kategori { get; set; }

    public virtual KitapDetay KitapDetay { get; set; }

    public virtual ICollection<Yorum> Yorum { get; set; }

}

}
