
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Sikayet
{

    public int Id { get; set; }

    public string Konu { get; set; }

    public string Açıklama { get; set; }

    public System.DateTime Tarih { get; set; }

    public int UserId { get; set; }



    public virtual User User { get; set; }

}

}
