
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Data
{

using System;
    using System.Collections.Generic;
    
public partial class Yorum
{

    public int Id { get; set; }

    public string Text { get; set; }

    public System.DateTime Tarih { get; set; }

    public bool Verified { get; set; }

    public int UserId { get; set; }

    public int KitapİlanId { get; set; }



    public virtual User User { get; set; }

    public virtual Kitapİlan Kitapİlan { get; set; }

}

}
